blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Default:index}

posts:
    path:     /posts/{username}
    defaults: { _controller: BlogBundle:Post:index, username: NULL }

post_new:
    path: /post/new
    defaults: {_controller: BlogBundle:Post:new}

user_registration:
    path:     /register
    defaults: { _controller: BlogBundle:Registration:register }

login_route:
    path:       /login
    defaults:   { _controller: BlogBundle:Security:login }

login_check:
    path:       /login_check
    defaults:   { _controller: BlogBundle:Security:loginCheck }

logout:
    path: /logout

